experiment:
  name: 'Solo_r50_fpn_3x'
  group: "v1"
  log_model: true
  wandb: None
  log_step: true


model: /content/drive/MyDrive/SOLO-implementation/configs/solo_v1.yaml


general:
  seed: 822
  gpus: [0]
  epoch: 36
  precision: 32
  data_root: ''
  trn_img_size:
    height: 256
    width: 256
  val_img_size:
    height: 256
    width: 256

  mean: [0.485, 0.456, 0.406]
  std:  [0.229, 0.224, 0.225]

  save_top_k: 5
  save_interval: 1



optim:
  name: 'SGD'
  args:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001


grad_clip:
  use: true
  max_norm: 35
  norm_type: 2


sched:
  name: 'MultiStepLR'
  args:
    milestones: [27, 33]
    gamma: 0.1


train_loader:
  image_path: 'cocodataset/train2017'
  annFile: '/content/drive/MyDrive/SOLO-implementation/instances_train2017.json'
  batch_size: 8
  num_workers: 8
  shuffle: trues


valid_loader:
  image_path: 'cocodataset/val2017'
  annFile: '/content/drive/MyDrive/SOLO-implementation/instances_val2017.json'
  batch_size: 8
  num_workers: 8
  shuffle: false